In [2]:
import os
import numpy as np
import pandas as pd
from glob import glob
from astropy.io import fits
from astropy.table import Table
from empirical_functions import spectrum, ModelFitting

# Initialize spectrum class with HST files
The data is interesting, I don't have older data, and the cspec files are weird.

In [ ]:
all_spectra.spec_df.keys()

Index(['filename', 'obsdate', 'instrument', 'filter', 'dispfile', 'LSFfile',
       'cenwave', 'wavelength', 'flux', 'fluxerr', 'segment', 'H2line_idx',
       '[nu', J']', 'labline', 'transition_prob'],
      dtype='object')

In [13]:
cspec_spectra.spec_df.keys()

Index(['filename', 'obsdate', 'instrument', 'filter', 'dispfile', 'LSFfile',
       'cenwave', 'wavelength', 'flux', 'fluxerr', 'segment', 'H2line_idx',
       '[nu', J']', 'labline', 'transition_prob'],
      dtype='object')

In [47]:
line_df.keys()

Index(['filename', 'obsdate', 'instrument', 'filter', 'dispfile', 'LSFfile',
       'cenwave', 'wavelength', 'flux', 'fluxerr', 'velocity', 'segment',
       'H2line_idx', 'labline', 'transition_prob', 'transition'],
      dtype='object')

In [2]:
cspec_files = glob(os.path.join('HST', 'anonymous37222', '*cspec.fits'))
cspec_spectra = spectrum(cspec_files, linelist_file='HST/emission_lines.csv', dataDir='HST/')
cspec_spectra.coaddwave(cspec_spectra.spec_df, columns = ['obsdate', 'filter'])
cspec_spectra.H2lines_fromspectrum(cspec_spectra.spec_df)

,filename,obsdate,instrument,filter,dispfile,LSFfile,cenwave,wavelength,flux,fluxerr,segment,H2line_idx,"[nu', J']",labline,transition_prob
0,HST/anonymous37222/hst_16110_cos_v-ru-lup_cg23...,2021-08-12,COS,G230L,None,None,MULTI,"[1413.6094970703125 Angstrom, 1414.0244140625 ...",[-1.1882458572642918e-08 erg / (Angstrom s cm2...,[3.5922305367940494e-09 erg / (Angstrom s cm2)...,None,"[469, 486, 4, 231, 483, 11, 242, 433, 500, 153...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
1,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-13,COS,G160M-G230L,None,None,MULTI,"[1395.40234375 Angstrom, 1395.41455078125 Angs...",[-2.343575556110751e-17 erg / (Angstrom s cm2)...,[3.5069690744130666e-15 erg / (Angstrom s cm2)...,None,"[17378, 17958, 1626, 9308, 17840, 1863, 9679, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
2,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-16,COS,G160M,None,None,MULTI,"[1395.4390869140625 Angstrom, 1395.45129394531...","[7.786828094217407e-15 erg / (Angstrom s cm2),...","[5.506211218443105e-15 erg / (Angstrom s cm2),...",None,"[17375, 17955, 1623, 9305, 17837, 1860, 9676, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
3,HST/anonymous37222/hst_16110_cos_v-ru-lup_cg23...,2021-08-15,COS,G230L,None,None,MULTI,"[1402.409423828125 Angstrom, 1402.824340820312...",[-3.960328953667158e-09 erg / (Angstrom s cm2)...,"[5.138981038487556e-09 erg / (Angstrom s cm2),...",None,"[496, 513, 31, 258, 510, 38, 269, 460, 527, 18...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
4,HST/anonymous37222/hst_16110_cos_v-ru-lup_cg23...,2021-08-21,COS,G230L,None,None,MULTI,"[1418.1739501953125 Angstrom, 1418.5888671875 ...",[-9.095240116607783e-09 erg / (Angstrom s cm2)...,"[3.591790918298872e-09 erg / (Angstrom s cm2),...",None,"[458, 475, 220, 472, 0, 231, 422, 489, 142, 26...","[[3,13], [3,13], [4,13], [4,13], [3,16], [3,16...","[1608.33, 1615.43, 1509.45, 1613.99, 1418.23, ...","[0.139, 0.125, 0.023, 0.092, 0.05, 0.057, 0.12..."
5,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-14,COS,G160M,None,None,MULTI,"[1395.3778076171875 Angstrom, 1395.39001464843...","[7.819889484214637e-15 erg / (Angstrom s cm2),...",[5.5295496206176025e-15 erg / (Angstrom s cm2)...,None,"[17380, 17960, 1628, 9310, 17842, 1865, 9681, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
6,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-21,COS,G160M,None,None,MULTI,"[1395.41455078125 Angstrom, 1395.4267578125 An...","[1.572425864645663e-14 erg / (Angstrom s cm2),...","[7.862200908491788e-15 erg / (Angstrom s cm2),...",None,"[17377, 17957, 1625, 9307, 17839, 1862, 9678, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
7,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-18,COS,G160M-G230L,None,None,MULTI,"[1395.4512939453125 Angstrom, 1395.46362304687...","[7.833256511155257e-15 erg / (Angstrom s cm2),...","[5.538997316936574e-15 erg / (Angstrom s cm2),...",None,"[17374, 17954, 1622, 9304, 17836, 1859, 9675, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
8,HST/anonymous37222/hst_12036_cos_v-ru-lupi_g13...,2012-02-28,COS,G130M,None,None,MULTI,"[1135.59619140625 Angstrom, 1135.606201171875 ...",[3.3927773412164176e-15 erg / (Angstrom s cm2)...,"[2.125946078252652e-15 erg / (Angstrom s cm2),...",None,"[28055, 28346, 29628, 31143, 30033, 26412, 267...","[[4,13], [3,16], [1,4], [1,4], [3,0], [0,1], [...","[1415.33, 1418.23, 1431.01, 1446.12, 1435.05, ...","[0.037, 0.05, 0.058, 0.083, 0.118, 0.141, 0.12..."
9,HST/anonymous37222/hst_12036_cos_v-ru-lupi_g16...,2011-07-20,COS,G160M,None,None,1611,"[1422.6502685546875 Angstrom, 1422.66259765625...",[1.6265634672496532e-14 erg / (Angstrom s cm2)...,[2.7960069763874706e-15 erg / (Angstrom s cm2)...,None,"[15167, 15747, 7090, 15629, 7461, 13936, 16212...","[[3,13], [3,13], [4,13], [4,13], [3,16], [3,16...","[1608.33, 1615.43, 1509.45, 1613.99, 1513.99, ...","[0.139, 0.125, 0.023, 0.092, 0.057, 0.122, 0.0..."
10,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-10,COS,G160M-G230L,None,None,MULTI,"[1395.537109375 Angstrom, 1395.54931640625 Ang...","[3.09713099418585e-14 erg / (Angstrom s cm2), ...","[9.825474803385942e-15 erg / (Angstrom s cm2),...",None,"[17367, 17947, 1615, 9297, 17829, 1852, 9668, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
11,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-15,COS,G160M,None,None,MULTI,"[1395.54931640625 Angstrom, 1395.5616455078125...",[2.3672920855576443e-14 erg / (Angstrom s cm2)...,"[9.664446044472983e-15 erg / (Angstrom s cm2),...",None,"[17366, 17946, 1614, 9296, 17828, 1851, 9667, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
12,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-15,COS,G160M-G230L,None,None,MULTI,"[1395.5616455078125 Angstrom, 1395.57385253906...",[3.1558255493427737e-14 erg / (Angstrom s cm2)...,[1.1157554673252939e-14 erg / (Angstrom s cm2)...,None,"[17365, 17945, 1613, 9295, 17827, 1850, 9666, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
13,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-10,COS,G160M,None,None,MULTI,"[1395.328857421875 Angstrom, 1395.341064453125...","[3.146919506122163e-14 erg / (Angstrom s cm2),...",[1.1126062084868046e-14 erg / (Angstrom s cm2)...,None,"[17384, 17964, 1632, 9314, 17846, 1869, 9685, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
14,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-13,COS,G160M,None,None,MULTI,"[1395.3900146484375 Angstrom, 1395.40234375 An...","[3.931575253074762e-14 erg / (Angstrom s cm2),...",[1.2432773177110696e-14 erg / (Angstrom s cm2)...,None,"[17379, 17959, 1627, 9309, 17841, 1864, 9680, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
15,HST/anonymous37222/hst_16110_cos_v-ru-lup_cg23...,2021-08-14,COS,G230L,None,None,MULTI,"[1399.9183349609375 Angstrom, 1400.33325195312...","[3.231153122840169e-09 erg / (Angstrom s cm2),...","[7.228728244267295e-09 erg / (Angstrom s cm2),...",None,"[502, 519, 37, 264, 516, 44, 275, 466, 533, 18...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
16,HST/anonymous37222/hst_16110_cos_v-ru-lup_cg23...,2021-08-18,COS,G230L,None,None,MULTI,"[1416.5140380859375 Angstrom, 1416.92895507812...","[6.74281519508213e-09 erg / (Angstrom s cm2), ...","[6.980750997967594e-09 erg / (Angstrom s cm2),...",None,"[462, 479, 224, 476, 4, 235, 426, 493, 146, 26...","[[3,13], [3,13], [4,13], [4,13], [3,16], [3,16...","[1608.33, 1615.43, 1509.45, 1613.99, 1418.23, ...","[0.139, 0.125, 0.023, 0.092, 0.05, 0.057, 0.12..."
17,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-14,COS,G160M-G230L,None,None,MULTI,"[1395.3900146484375 Angstrom, 1395.40234375 An...","[3.14061487048916e-14 erg / (Angstrom s cm2), ...",[1.1103794660811226e-14 erg / (Angstrom s cm2)...,None,"[17379, 17959, 1627, 9309, 17841, 1864, 9680, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
18,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-21,COS,G160M-G230L,None,None,MULTI,"[1395.4267578125 Angstrom, 1395.4390869140625 ...",[3.9369966027503686e-14 erg / (Angstrom s cm2)...,"[1.244992804685814e-14 erg / (Angstrom s cm2),...",None,"[17376, 17956, 1624, 9306, 17838, 1861, 9677, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
19,HST/anonymous37222/hst_12036_cos_v-ru-lupi_g16...,2012-02-28,COS,G160M,None,None,MULTI,"[1399.850341796875 Angstrom, 1399.862670898437...",[5.0242758765266585e-14 erg / (Angstrom s cm2)...,[4.9832787525244805e-15 erg / (Angstrom s cm2)...,None,"[17024, 17604, 1264, 8950, 17486, 1501, 9320, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
20,HST/anonymous37222/hst_12036_cos_v-ru-lupi_g13...,2012-02-28,COS,G130M-G160M,None,None,MULTI,"[1135.606201171875 Angstrom, 1135.616088867187...",[-2.772991184081609e-16 erg / (Angstrom s cm2)...,[1.4716896302732866e-15 erg / (Angstrom s cm2)...,None,"[44610, 45190, 28054, 36536, 45072, 28345, 369...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
21,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-11,COS,G160M,None,None,MULTI,"[1395.475830078125 Angstrom, 1395.488159179687...",[-8.496361839036782e-17 erg / (Angstrom s cm2)...,[3.5085652679974346e-15 erg / (Angstrom s cm2)...,None,"[17372, 17952, 1620, 9302, 17834, 1857, 9673, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
22,HST/anonymous37222/hst_16110_cos_v-ru-lup_cg23...,2021-08-11,COS,G230L,None,None,MULTI,"[1401.166748046875 Angstrom, 1401.581787109375...",[-1.6516823464485242e-09 erg / (Angstrom s cm2...,"[5.124037907942307e-09 erg / (Angstrom s cm2),...",None,"[499, 516, 34, 261, 513, 41, 272, 463, 530, 18...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
23,HST/anonymous37222/hst_16592_cos_v-ru-lup_cg23...,2022-08-10,COS,G230L,None,None,MULTI,"[1389.9617919921875 Angstrom, 1390.37670898437...",[1.6841754657548336e-09 erg / (Angstrom s cm2)...,"[7.195592411183563e-09 erg / (Angstrom s cm2),...",None,"[526, 543, 61, 288, 540, 68, 299, 490, 557, 21...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
24,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-17,COS,G160M-G230L,None,None,MULTI,"[1395.341064453125 Angstrom, 1395.353271484375...","[2.359806516589579e-14 erg / (Angstrom s cm2),...","[9.63388324409035e-15 erg / (Angstrom s cm2), ...",None,"[17383, 17963, 1631, 9313, 17845, 1868, 9684, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
25,HST/anonymous37222/hst_16110_cos_v-ru-lup_cg23...,2021-08-10,COS,G230L,None,None,MULTI,"[1397.016357421875 Angstrom, 1397.431274414062...",[-6.079762027155766e-09 erg / (Angstrom s cm2)...,"[5.152730988284242e-09 erg / (Angstrom s cm2),...",None,"[509, 526, 44, 271, 523, 51, 282, 473, 540, 19...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
26,HST/anonymous37222/hst_16110_cos_v-ru-lup_cg23...,2021-08-17,COS,G230L,None,None,MULTI,"[1397.013671875 Angstrom, 1397.4285888671875 A...",[-6.079762027155766e-09 erg / (Angstrom s cm2)...,"[5.152730988284242e-09 erg / (Angstrom s cm2),...",None,"[509, 526, 44, 271, 523, 51, 282, 473, 540, 19...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
27,HST/anonymous37222/hst_8157_stis_hd142560_e140...,2000-07-12,STIS,E140M-G430L,None,None,MULTI,"[1141.602294921875 Angstrom, 1141.620727539062...",[-5.424865309570925e-12 erg / (Angstrom s cm2)...,[1.3525695168729782e-12 erg / (Angstrom s cm2)...,None,"[25341, 25727, 14862, 19972, 25648, 15020, 202...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
28,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-20,COS,G160M-G230L,None,None,MULTI,"[1395.4512939453125 Angstrom, 1395.46362304687...","[7.846177151732674e-15 erg / (Angstrom s cm2),...",[5.5481324408358305e-15 erg / (Angstrom s cm2)...,None,"[17374, 17954, 1622, 9304, 17836, 1859, 9675, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
29,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-16,COS,G160M-G230L,None,None,MULTI,"[1395.4512939453125 Angstrom, 1395.46362304687...","[7.784802838440522e-15 erg / (Angstrom s cm2),...","[5.504779145472877e-15 erg / (Angstrom s cm2),...",None,"[17374, 17954, 1622, 9304, 17836, 1859, 9675, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
30,HST/anonymous37222/hst_8157_stis_hd142560_e140...,2000-07-12,STIS,E140M,None,None,1425,"[1140.497314453125 Angstrom, 1140.515747070312...",[-1.5094661978687363e-10 erg / (Angstrom s cm2...,[1.5418678944326007e-10 erg / (Angstrom s cm2)...,None,"[25401, 25787, 14922, 20032, 25708, 15080, 202...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
31,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-12,COS,G160M,None,None,MULTI,"[1395.5738525390625 Angstrom, 1395.58605957031...",[2.3618717523215746e-14 erg / (Angstrom s cm2)...,"[9.642340863131392e-15 erg / (Angstrom s cm2),...",None,"[17364, 17944, 1612, 9294, 17826, 1849, 9665, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
32,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-17,COS,G160M,None,None,MULTI,"[1395.328857421875 Angstrom, 1395.341064453125...","[3.146919506122163e-14 erg / (Angstrom s cm2),...",[1.1126062084868046e-14 erg / (Angstrom s cm2)...,None,"[17384, 17964, 1632, 9314, 17846, 1869, 9685, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
33,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-12,COS,G160M-G230L,None,None,MULTI,"[1395.5860595703125 Angstrom, 1395.59838867187...","[7.844067192661064e-15 erg / (Angstrom s cm2),...","[5.546637442693923e-15 erg / (Angstrom s cm2),...",None,"[17363, 17943, 1611, 9293, 17825, 1848, 9664, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
34,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-11,COS,G160M-G230L,None,None,MULTI,"[1395.4881591796875 Angstrom, 1395.50036621093...",[-8.495896632660282e-17 erg / (Angstrom s cm2)...,"[3.508632933132529e-15 erg / (Angstrom s cm2),...",None,"[17371, 17951, 1619, 9301, 17833, 1856, 9672, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
35,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-20,COS,G160M,None,None,MULTI,"[1395.4390869140625 Angstrom, 1395.45129394531...",[1.5714934507773254e-14 erg / (Angstrom s cm2)...,"[7.85753943495468e-15 erg / (Angstrom s cm2), ...",None,"[17375, 17955, 1623, 9305, 17837, 1860, 9676, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
36,HST/anonymous37222/hst_16110_cos_v-ru-lup_g160...,2021-08-18,COS,G160M,None,None,MULTI,"[1395.4390869140625 Angstrom, 1395.45129394531...","[1.571215285157447e-14 erg / (Angstrom s cm2),...","[7.856148704155391e-15 erg / (Angstrom s cm2),...",None,"[17375, 17955, 1623, 9305, 17837, 1860, 9676, ...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
37,HST/anonymous37222/hst_8157_stis_hd142560_g430...,2000-07-12,STIS,G430L,None,None,4300,"[2985.4638671875 Angstrom, 2988.208984375 Angs...",[4.0675271581903233e-13 erg / (Angstrom s cm2)...,[4.3378758290994255e-15 erg / (Angstrom s cm2)...,None,[],[],[],[]
38,HST/anonymous37222/hst_16110_cos_v-ru-lup_cg23...,2021-08-20,COS,G230L,None,None,MULTI,"[1401.16552734375 Angstrom, 1401.5804443359375...","[4.775200679318914e-09 erg / (Angstrom s cm2),...","[7.232671737449716e-09 erg / (Angstrom s cm2),...",None,"[499, 516, 34, 261, 513, 41, 272, 463, 530, 18...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
39,HST/anonymous37222/hst_16110_cos_v-ru-lup_cg23...,2021-08-16,COS,G230L,None,None,MULTI,"[1399.0870361328125 Angstrom, 1399.50183105468...",[2.6484108239799298e-09 erg / (Angstrom s cm2)...,[7.2143625956060305e-09 erg / (Angstrom s cm2)...,None,"[504, 521, 39, 266, 518, 46, 277, 468, 535, 18...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
40,HST/anonymous37222/hst_16110_cos_v-ru-lup_cg23...,2021-08-13,COS,G230L,None,None,MULTI,"[1403.6513671875 Angstrom, 1404.0662841796875 ...","[2.119930231359035e-09 erg / (Angstrom s cm2),...","[7.379815769393872e-09 erg / (Angstrom s cm2),...",None,"[493, 510, 28, 255, 507, 35, 266, 457, 524, 17...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."

In [61]:
#Table showing proposalID, lifetime position, observation date, filter, Calibration pipeline, image type
# PROPOSID, LIFE_ADJ, DATE, OPT_ELEM, OPUS_VER, IMAGETYP
x1dsum_files = glob(os.path.join('HST', 'anonymous37222', '*x1dsum.fits'))
propid = []
lp = []
date = []
filt = []
cal_ver = []
imtyp = []
rootname = []
for file in x1dsum_files:
    pri = fits.open(file)[0].header
    if pri['TARGNAME']!='SZ82':
        propid.append(pri['PROPOSID'])
        lp.append(pri['LIFE_ADJ'])
        date.append(pri['DATE'])
        filt.append(pri['OPT_ELEM'])
        cal_ver.append(pri['OPUS_VER'])
        imtyp.append(pri['IMAGETYP'])
        #print(pri['PR_INV_L'], pri['PR_INV_F'], pri['PR_INV_M'])
        rootname.append(pri['ROOTNAME'])
    else:
        print(file)
        
    
colnames = ['Proposal ID', 'Date', 'COS Filter', 'Lifetime Position', 'Data Pipeline Version', 'Image Type']
obs_data = np.transpose([propid, date, filt, lp, cal_ver, imtyp])
obs_df = pd.DataFrame(obs_data, columns = colnames)
obs_df = obs_df.drop_duplicates()

In [2]:
x1dsum_files = glob(os.path.join('HST', 'anonymous37222', '*x1dsum.fits'))
all_spectra = spectrum(x1dsum_files, linelist_file='HST/emission_lines.csv', dataDir='HST/')
all_spectra.coaddwave(all_spectra.spec_df, columns = ['obsdate', 'filter'])
all_spectra.H2lines_fromspectrum(all_spectra.spec_df)

,filename,obsdate,instrument,filter,dispfile,LSFfile,cenwave,wavelength,flux,fluxerr,segment,H2line_idx,"[nu', J']",labline,transition_prob
0,HST/anonymous37222/lbgj02040_x1dsum.fits,2011-07-20,COS,G130M,HST/05i1639ml_disp.fits,HST/aa_LSFTable_G130M_1291_LP1_cn.dat,1291,"[1124.7185766387568 Angstrom, 1124.72853832954...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1277.973751578046, 1441.2228355636628], [112...","[30169, 30460, 31742, 32148, 28525, 28896, 320...","[[4,13], [3,16], [1,4], [3,0], [0,1], [0,2], [...","[1415.33, 1418.23, 1431.01, 1435.05, 1398.95, ...","[0.037, 0.05, 0.058, 0.118, 0.141, 0.126, 0.06..."
1,HST/anonymous37222/lbgj02080_x1dsum.fits,2011-07-20,COS,G160M,HST/05i1639ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP1_cn.dat,1589,"[1386.0412954067515 Angstrom, 1386.05353027634...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.2079430415886, 1774.7234919417112], [13...","[19172, 19752, 2394, 10087, 19634, 2631, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
2,HST/anonymous37222/lbgj53040_x1dsum.fits,2012-02-28,COS,G130M,HST/05i1639ml_disp.fits,HST/aa_LSFTable_G130M_1291_LP1_cn.dat,1291,"[1124.9096635174221 Angstrom, 1124.91962690073...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1278.1908850506225, 1441.4677056605317], [11...","[30144, 30435, 31718, 32123, 28501, 28872, 320...","[[4,13], [3,16], [1,4], [3,0], [0,1], [0,2], [...","[1415.33, 1418.23, 1431.01, 1435.05, 1398.95, ...","[0.037, 0.05, 0.058, 0.118, 0.141, 0.126, 0.06..."
3,HST/anonymous37222/lbgj53080_x1dsum.fits,2012-02-28,COS,G160M,HST/05i1639ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP1_cn.dat,1589,"[1386.2769487823698 Angstrom, 1386.28918573199...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.475576544502, 1775.0252147764359], [138...","[19150, 19730, 2374, 10066, 19612, 2611, 10437...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
4,HST/anonymous37222/leit1c030_x1dsum.fits,2021-08-10,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9946471407397 Angstrom, 1386.00688689571...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1775650550824, 1774.8296525079247], [13...","[19173, 19752, 2397, 10086, 19635, 2634, 10457...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
5,HST/anonymous37222/leit1d030_x1dsum.fits,2021-08-11,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9941396590698 Angstrom, 1386.00637941009...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.177039290039, 1774.8290620852715], [138...","[19173, 19752, 2397, 10086, 19635, 2634, 10457...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
6,HST/anonymous37222/leit1e030_x1dsum.fits,2021-08-12,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9934968299058 Angstrom, 1386.00573657483...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1763039542636, 1774.82822680399], [1385...","[19173, 19752, 2397, 10087, 19635, 2634, 10457...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
7,HST/anonymous37222/leit1f030_x1dsum.fits,2021-08-13,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9931276253203 Angstrom, 1386.00536736705...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1758709162705, 1774.8277413948108], [13...","[19173, 19752, 2397, 10087, 19635, 2634, 10457...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
8,HST/anonymous37222/leit1g030_x1dsum.fits,2021-08-14,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9926535426373 Angstrom, 1386.00489328013...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1753619262686, 1774.8271628899083], [13...","[19173, 19752, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
9,HST/anonymous37222/leit1h030_x1dsum.fits,2021-08-15,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9921658835162 Angstrom, 1386.00440561677...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1747588329204, 1774.8264902607607], [13...","[19173, 19752, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
10,HST/anonymous37222/leit1i030_x1dsum.fits,2021-08-16,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9916804390439 Angstrom, 1386.00392016811...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.174218929461, 1774.8258818508884], [138...","[19173, 19752, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
11,HST/anonymous37222/leit1j030_x1dsum.fits,2021-08-17,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9912497641506 Angstrom, 1386.00348948963...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1737601978853, 1774.825364228126], [138...","[19173, 19753, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
12,HST/anonymous37222/leit1k030_x1dsum.fits,2021-08-18,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9909603061985 Angstrom, 1386.00320002882...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1734280322964, 1774.824985216879], [138...","[19173, 19753, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
13,HST/anonymous37222/leit1m030_x1dsum.fits,2021-08-20,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9903407572133 Angstrom, 1386.00258047415...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.172712608624, 1774.824176621237], [1385...","[19173, 19753, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
14,HST/anonymous37222/leit1n030_x1dsum.fits,2021-08-21,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9900462627913 Angstrom, 1386.00228597737...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1723901491057, 1774.823815425727], [138...","[19173, 19753, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
15,HST/anonymous37222/leph1c030_x1dsum.fits,2022-08-10,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9951835939507 Angstrom, 1386.00742335376...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1782031017756, 1774.8303699895666], [13...","[19172, 19752, 2397, 10086, 19635, 2634, 10457...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
16,HST/anonymous37222/leph1d030_x1dsum.fits,2022-08-11,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9945485462765 Angstrom, 1386.00678830049...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1773861913039, 1774.8294612569728], [13...","[19173, 19752, 2397, 10086, 19635, 2634, 10457...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
17,HST/anonymous37222/leph1f030_x1dsum.fits,2022-08-13,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.993493706029 Angstrom, 1386.005733450934...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1763140376165, 1774.8282364555246], [13...","[19173, 19752, 2397, 10087, 19635, 2634, 10457...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
18,HST/anonymous37222/leph1g030_x1dsum.fits,2022-08-14,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9929259052471 Angstrom, 1386.00516564510...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.175598677498, 1774.827438367698], [1385...","[19173, 19752, 2397, 10087, 19635, 2634, 10457...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
19,HST/anonymous37222/leph1i030_x1dsum.fits,2022-08-15,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9921428581877 Angstrom, 1386.00438259114...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1747250689384, 1774.8264515686096], [13...","[19173, 19752, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
20,HST/anonymous37222/leph1j030_x1dsum.fits,2022-08-16,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9917161124404 Angstrom, 1386.00395584173...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1742425524706, 1774.8259091094505], [13...","[19173, 19752, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
21,HST/anonymous37222/leph1k030_x1dsum.fits,2022-08-17,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9913361240272 Angstrom, 1386.00357584994...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1738146602324, 1774.82542578561], [1385...","[19173, 19753, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
22,HST/anonymous37222/leph1l030_x1dsum.fits,2022-08-18,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9909696082839 Angstrom, 1386.00320933088...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1734227994093, 1774.8249795589593], [13...","[19173, 19753, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
23,HST/anonymous37222/leph1m030_x1dsum.fits,2022-08-19,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9906740586073 Angstrom, 1386.00291377859...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1730855192723, 1774.824599379086], [138...","[19173, 19753, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
24,HST/anonymous37222/leph1n030_x1dsum.fits,2022-08-20,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9903499442378 Angstrom, 1386.00258966149...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1726908729697, 1774.824160113908], [138...","[19173, 19753, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
25,HST/anonymous37222/lephad030_x1dsum.fits,2022-08-23,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9896587703408 Angstrom, 1386.00189848125...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1719548807457, 1774.8233200404297], [13...","[19173, 19753, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
26,HST/anonymous37222/lephae030_x1dsum.fits,2022-08-24,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1385.9894779844765 Angstrom, 1386.00171769397...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.1717301496085, 1774.8230720927218], [13...","[19173, 19753, 2397, 10087, 19635, 2634, 10458...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
27,HST/anonymous37222/leso2c010_x1dsum.fits,2022-06-16,COS,G160M,HST/2bj2256ml_disp.fits,HST/aa_LSFTable_G160M_1589_LP4_cn.dat,1589,"[1386.075555441118 Angstrom, 1386.087795910712...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1574.2695000413048, 1774.9333026340148], [13...","[19165, 19745, 2390, 10079, 19627, 2627, 10450...","[[3,13], [3,13], [4,13], [4,13], [4,13], [3,16...","[1608.33, 1615.43, 1415.33, 1509.45, 1613.99, ...","[0.139, 0.125, 0.037, 0.023, 0.092, 0.05, 0.05..."
28,HST/anonymous37222/leso2c020_x1dsum.fits,2022-06-16,COS,G130M,HST/5992009ol_disp.fits,HST/aa_LSFTable_G130M_1291_LP5_cn.dat,1291,"[1124.122411192166 Angstrom, 1124.132378553306...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[0.0 erg / (Angstrom s cm2), 0.0 erg / (Angstr...","[[1277.3623641485256, 1440.6790191373045], [11...","[30224, 30515, 31797, 32202, 28581, 28952, 321...","[[4,13], [3,16], [1,4], [3,0], [0,1], [0,2], [...","[1415.33, 1418.23, 1431.01, 1435.05, 1398.95, ...","[0.037, 0.05, 0.058, 0.118, 0.141, 0.126, 0.06..."

# Compile properties of individual lines

In [3]:
all_spectra.spec_df = all_spectra.spec_df[all_spectra.spec_df["[nu', J']"].notna() & (all_spectra.spec_df["[nu', J']"].apply(len) > 0)] #remove the spectra (coadded for one observation date) that don't have any H2 lines
line_df = all_spectra.get_lines(all_spectra.spec_df) #rearrange df by progressions, not obsdate

In [4]:
cspec_spectra.spec_df = cspec_spectra.spec_df[cspec_spectra.spec_df["[nu', J']"].notna() & (cspec_spectra.spec_df["[nu', J']"].apply(len) > 0)] #remove the spectra (coadded for one observation date) that don't have any H2 lines
line_df = cspec_spectra.get_lines(cspec_spectra.spec_df) #rearrange df by progressions, not obsdate

NameError: name 'cspec_spectra' is not defined

# Look for contaminated lines
Transitions we have:
{'[0,3]', '[2,12]', '[0,2]', '[1,7]', '[4,13]', '[0,1]', '[3,16]', '[2,15]', '[1,4]', '[3,0]', '[4,4]', '[3,13]'}

Remove the noisy lines with very low SNR. This was done by eye, not an SNR cut.

In [6]:
exclude_lines = {
    "[0,1]": {
        "dates": ["2022-08-11", "2022-08-24", "2011-07-20", "2021-08-11", 
                  "2021-08-11", "2021-08-11", "2011-07-20", "2012-02-28", 
                  "2012-02-28", "2021-08-16", "2022-08-14", "2022-08-11",
                  "2022-08-11"],
        "wavelengths": [1460.17, 1521.59, 1521.59, 1398.95,
                        1460.17, 1521.59, 1398.95, 1521.59, 
                        1398.95, 1521.59, 1521.59, 1398.95, 
                        1521.59]
    },
    "[0,2]": {
        "dates": ["2022-08-11", "2021-08-11", "2021-08-11", "2012-02-28", "All", "All"],
        "wavelengths": [1463.83, 1402.65, 1463.83, 1402.65, 1525.15, 1402.65] #1402.65 line contaminated by Si IV
    },
    "[1,4]": {
        "dates": ["2022-08-11", "2021-08-11", "2021-08-11", "2021-08-11", "2021-08-11"],
        "wavelengths": [1431.01, 1431.01, 1446.12, 1489.57, 1504.76]
    },
    "[3,0]": {
        "dates": [
            "2021-08-10", "2021-08-11", "2021-08-11", "2021-08-12",
            "2022-08-11", "2022-08-11", "2022-08-13", "2012-02-28",
            "All"
        ],
        "wavelengths": [
            1636.34, 1591.32, 1636.34, 1636.34,
            1591.32, 1636.34, 1591.32, 1591.32,
            1435.05
        ]
    },
    "[1,7]": {
        "dates": ["All", "All", "2022-08-11", "2022-08-11", "2021-08-11", "2021-08-11"],
        "wavelengths": [1556.87, 1524.65, 1467.08, 1500.45, 1467.08, 1500.45]
    },
    "[2,12]": {
        'dates': ['2021-08-18', '2021-08-18', '2022-06-16', '2022-08-11', 
                  '2022-08-11', '2021-08-20', '2011-07-20', '2021-08-11', 
                  '2021-08-11', '2012-02-28', '2021-08-12', "All", "All"],
        "wavelengths": [1555.89, 1588.8, 1555.89, 1555.89, 
                        1588.8, 1555.89, 1588.8, 1555.89, 
                        1588.8, 1555.89, 1555.89, 1434.54, 1453.1]
    },
    "[4,13]": {
        "dates": [
            "2011-07-20", "All", "2021-08-10", "2021-08-11",
            "2021-08-14", "2021-08-16", "2021-08-17", "2022-08-11",
            "2022-08-13", "2022-08-24", "2022-06-16", "All"
        ],
        "wavelengths": [
            1415.33, 1509.45, 1415.33, 1415.33,
            1415.33, 1415.33, 1415.33, 1415.33,
            1415.33, 1415.33, 1415.33, 1613.99
        ]
    },
    "[3,13]": {
        "dates": [
            "All", "2012-02-28", "2021-08-11", "2022-08-11", "2022-08-15",
            "2022-08-16", "2022-08-17", "2022-08-18", "2022-08-20", "2022-08-23",
            "2022-08-24", "2022-06-16"
        ],
        "wavelengths": [
            1615.43, 1608.33, 1608.33, 1608.33, 1608.33,
            1608.33, 1608.33, 1608.33, 1608.33, 1608.33,
            1608.33, 1608.33
        ]
    },
    "[4,4]": {
        "dates": ["All", "2021-08-10", "2021-08-11", "2022-08-11", "2022-08-11", "All"],
        "wavelengths": [1477.05, 1613.72, 1613.72, 1613.72, 1477.05, 1526.55]
    },
    "[0,3]": {
        "dates": [
            "All", "2021-08-11", "2021-08-20", "2021-08-11", "2021-08-11",
            "2022-06-16", "2022-08-11", "2022-08-24", "2022-08-16",
            "2011-07-20", "2022-08-23", "2012-02-28", "2021-08-21",
            "2022-08-19", "2022-08-19", "2022-08-12", "2022-06-16",
            "2022-08-14", "2022-08-18", "2021-08-17"

        ],
        "wavelengths": [
            1395.2, 1468.39, 1407.29, 1407.29, 1468.39,
            1468.39, 1468.39, 1468.39, 1407.29,
            1468.39, 1468.39, 1468.39, 1407.29,
            1407.29, 1468.39, 1407.29, 1407.29,
            1468.39, 1468.39, 1468.39
        ]
    }
}

In [7]:
# exclude bad/contaminated lines from coadding
bad_transitions = ['[3,16]', '[4,0]', '[3,13]', '[2,15]'] #938 -> 426 lines in line_df
bad_transitions_mask = ~line_df['transition'].isin(bad_transitions)
line_df = line_df[bad_transitions_mask]

contaminated = []
for transition in exclude_lines.keys():
    dates = exclude_lines[transition]['dates']
    lines_ex = exclude_lines[transition]['wavelengths']
    for d, w in zip(dates, lines_ex):
        if d == "All":
            exclude_idx = line_df.index[(line_df['transition']==transition)&(line_df['labline']==w)].tolist()
        else:
            exclude_idx = line_df.index[(line_df['transition']==transition)&(line_df['labline']==w)&(line_df['obsdate']==d)].tolist()
        contaminated.extend(exclude_idx)

line_df = line_df.drop(index=contaminated)

line_df = line_df[line_df['obsdate']!='2021-08-11']
#Drop duplicates
line_df = line_df[~line_df.duplicated(['obsdate', 'transition', 'labline'])].reset_index(drop=True)

In [8]:
#Separate out blue transitions
blue_transitions = {'[4,13]', '[4,4]'}
mask = line_df['transition'].isin(blue_transitions)
blue_df = line_df[mask].copy() #146 lines
all_spectra.coaddwave(blue_df, columns=['labline', 'obsdate']) #39 lines

In [9]:
#Separate out red transitions
red_transitions = {'[2,12]', '[0,3]'}
red_df = line_df[line_df['transition'].isin(red_transitions)].copy() #130 lines
all_spectra.coaddwave(red_df, columns=['labline', 'obsdate']) #76 lines

In [10]:
#Remove blue and red transitions from main df
br_transitions = ['[2,12]', '[4,13]', '[4,4]', '[0,3]']
bad_transitions_mask = ~line_df['transition'].isin(br_transitions)
line_df = line_df[bad_transitions_mask].reset_index(drop=True)
all_spectra.coaddwave(line_df, columns=['labline', 'obsdate']) #236 lines

In [12]:
len(line_df)+len(red_df)+len(blue_df)

395

In [21]:
# labline: mask array
line_mask_dict = {
    1453.1:200,
    1555.89:[75,175],
    1463.83:200,
    1613.72:[75,200],
    1415.33:180,
    1407.29:200,
    1468.39:[75,299], #mask out MgII transition at 1466.55
    1407.29: [75,250],
    1435.05: [80,299], #High velocity component
    1636.34: [75,190]
}
def mask_contamination(labline, mask_dict):
    mask_idx = mask_dict[labline]
    if isinstance(mask_idx, list):
        mask=np.ones(300, dtype=bool)
        mask[mask_idx[0]:mask_idx[1]] = False
        return mask
    else:
        mask=np.zeros(300, dtype=bool)
        mask[mask_idx:] = True
        return mask

def get_continuum(row):
    if row['labline'] in line_mask_dict.keys():
        mask = mask_contamination(row['labline'], line_mask_dict)
        x_masked, y_masked = row['wavelength'][~mask], row['flux'][~mask]
        #pull out background
        x_fit, y_fit = x_masked[:40].value, y_masked[:40].value
    else:
        x_fit, y_fit = np.concatenate(row['wavelength'][:40].value, row['wavelength'][-20:].value) , np.concatenate(row['flux'][:40].value, row['flux'][-20:].value)

    #fit to background
    p = np.polyfit(x_fit, y_fit, 1)
    #get continuum over the whole line
    continuum_fluxes = p[1] + (row['wavelength'].value*p[0])
    return continuum_fluxes

# Co-add by lablines and by years

In [13]:
red_df_coadded = all_spectra.coadd_lines(red_df)
blue_df_coadded = all_spectra.coadd_lines(blue_df)
line_df_coadded = all_spectra.coadd_lines(line_df)

# Model the emission lines and save the parameters

In [36]:
#build dataframe for convolution information
def make_disp_df(files):
    disptable_info = []
    for file in files:
        disptable = fits.open(file, ignore_missing_simple=True)[1].data
        disptable = disptable[disptable['aperture']=="PSA"]
        cols = {}
        for col in ['SEGMENT', 'CENWAVE', 'OPT_ELEM','COEFF', 'D_TV03', 'D']:
            cols[col] = disptable[col]
        cols['disptab']=file
        disptable_info.append(cols)
    disp_df = pd.DataFrame(disptable_info).set_index('disptab')
    return disp_df

def make_lsf_df(files):
    lsf_info = []
    for file in files:
        # This is the table of all the LSFs: called "lsf"
        # The first column is a list of the wavelengths corresponding to the line profile, so we set our header accordingly
        hs = 0
        lsf = Table.read(file, format="ascii", header_start=hs)

        # This is the range of each LSF in pixels (for FUV from -160 to +160, inclusive)
        # middle pixel of the lsf is considered zero ; center is relative zero
        pix = np.arange(len(lsf)) - len(lsf) // 2  # integer division to yield whole pixels

        # the column names returned as integers.
        lsf_wvlns = np.array([int(float(k)) for k in lsf.keys()])
        lsf_info.append({'lsf_file':file, 'lsf':lsf, 'pix':pix, 'w':lsf_wvlns})
    lsf_df = pd.DataFrame(lsf_info).set_index('lsf_file')
    return lsf_df

disp_df = make_disp_df(set(list(set(line_df['dispfile']))+list(set(blue_df['dispfile']))+list(set(red_df['dispfile']))))
lsf_df = make_lsf_df(set(list(set(line_df['LSFfile']))+list(set(blue_df['LSFfile']))+list(set(red_df['LSFfile']))))

In [32]:
#disp_df.to_pickle(os.path.join('data','disp_df.pkl'))
#lsf_df.to_pickle(os.path.join('data','lsf_df.pkl'))
disp_df = pd.read_pickle('data/disp_df.pkl')
lsf_df = pd.read_pickle('data/lsf_df.pkl')

In [13]:
initial_guess_line_df = {
    1521.59: {'amp1':{'init':1e-13, 'min':5e-14, 'max':2e-13},
                     'sig1':{'init':5e-2, 'min':0.02, 'max':0.08},
                     'cen1':{'init':1521.59, 'min':1521.59-0.5, 'max':1521.59+0.5},
                     'amp2':{'init':4e-14, 'min':None, 'max':5e-14},
                     'sig2':{'init':0.1, 'min':0.08, 'max':0.5},
                     'cen2':{'init':1521.59, 'min':1521.59-0.5, 'max':1521.59+0.5},
                     'bgl':{'init':4.8e-14, 'min':None, 'max':None}},

    1463.83: {'amp1':{'init':5e-13, 'min':2e-13, 'max':8e-12},
                     'sig1':{'init':5.5e-2, 'min':4.8e-2, 'max':7e-2},
                     'cen1':{'init':1463.83, 'min':1463.83-0.5, 'max':1463.83+0.5},
                     'amp2':{'init':1.5e-13, 'min':1e-13, 'max':2e-13},
                     'sig2':{'init':1.8e-1, 'min':1.5e-1, 'max':2e-1},
                     'cen2':{'init':1463.83, 'min':1463.83-0.5, 'max':1463.83+0.5},
                     'bgl':{'init':5e-14, 'min':None, 'max':None}},

    1460.17: {'amp1':{'init':8.5e-13, 'min':3e-13, 'max':9e-13},
                     'sig1':{'init':3e-2, 'min':1.5e-2, 'max':5.6e-2},
                     'cen1':{'init':1460.17, 'min':1460.17-0.5, 'max':1460.17+0.5},
                     'amp2':{'init':7.5e-14, 'min':6e-14, 'max':2.9e-13},
                     'sig2':{'init':1e-1, 'min':5.6e-2, 'max':2e-1},
                     'cen2':{'init':1460.17, 'min':1460.17-0.5, 'max':1460.17+0.5},
                     'bgl':{'init':8e-13, 'min':None, 'max':None}},

    1398.95: {'amp1':{'init':4.5e-13, 'min':3e-13, 'max':7e-13},
                     'sig1':{'init':3e-2, 'min':1e-2, 'max':5.5e-2},
                     'cen1':{'init':1398.95, 'min':1398.95-0.5, 'max':1398.95+0.5},
                     'amp2':{'init':2e-13, 'min':1e-13, 'max':2.9e-13},
                     'sig2':{'init':1e-1, 'min':5.6e-2, 'max':2e-1},
                     'cen2':{'init':1398.95, 'min':1398.95-0.5, 'max':1398.95+0.5},
                     'bgl':{'init':4e-14, 'min':None, 'max':None}},

    1636.34: {'amp1':{'init':1.65e-13, 'min':6.9e-14, 'max':2.5e-13},
                     'sig1':{'init':1e-1, 'min':6e-2, 'max':1.5e-1},
                     'cen1':{'init':1636.34, 'min':1636.34-0.5, 'max':1636.34+0.5},
                     'amp2':{'init':6.5e-14, 'min':6.2e-14, 'max':6.9e-14},
                     'sig2':{'init':5e-2, 'min':3e-2, 'max':6e-2}, #this one the shorter comp. is narrower too
                     'cen2':{'init':1636.34, 'min':1636.34-0.5, 'max':1636.34+0.5},
                     'bgl':{'init':5e-14, 'min':None, 'max':None}},

    1591.32: {'amp1':{'init':1.75e-13, 'min':9e-14, 'max':3e-13},
                     'sig1':{'init':1.5e-1, 'min':8e-2, 'max':2.5e-1},
                     'cen1':{'init':1591.32, 'min':1591.32-0.5, 'max':1591.32+0.5},
                     'amp2':{'init':6e-14, 'min':5e-14, 'max':8.9e-14},
                     'sig2':{'init':4.5e-2, 'min':1e-2, 'max':8e-2},
                     'cen2':{'init':1591.32, 'min':1591.32-0.5, 'max':1591.32+0.5},
                     'bgl':{'init':7e-14, 'min':None, 'max':None}},

    1431.01: {'amp1':{'init':1e-13, 'min':8e-14, 'max':3.8e-13},
                     'sig1':{'init':5e-2, 'min':4e-2, 'max':7e-2},
                     'cen1':{'init':1431.01, 'min':1431.01-0.5, 'max':1431.01+0.5},
                     'amp2':{'init':8.5e-14, 'min':4e-14, 'max':1.5e-13},
                     'sig2':{'init':1.3e-1, 'min':7e-2, 'max':1.9e-1},
                     'cen2':{'init':1431.01, 'min':1431.01-0.5, 'max':1431.01+0.5},
                     'bgl':{'init':3e-14, 'min':None, 'max':None}},

    1446.12: {'amp1':{'init':6.5e-13, 'min':3e-13, 'max':1e-12},
                     'sig1':{'init':6.3e-2, 'min':5.3e-2, 'max':7e-2},
                     'cen1':{'init':1446.12, 'min':1446.12-0.5, 'max':1446.12+0.5},
                     'amp2':{'init':2e-13, 'min':1e-13, 'max':3e-13},
                     'sig2':{'init':1.5e-1, 'min':7e-2, 'max':3e-1},
                     'cen2':{'init':1446.12, 'min':1446.12-0.5, 'max':1446.12+0.5},
                     'bgl':{'init':5e-14, 'min':None, 'max':None}},

    1489.57: {'amp1':{'init':6.5e-13, 'min':4e-13, 'max':1.3e-12},
                     'sig1':{'init':6e-2, 'min':5e-2, 'max':7e-2},
                     'cen1':{'init':1489.57, 'min':1489.57-0.5, 'max':1489.57+0.5},
                     'amp2':{'init':1.5e-13, 'min':1e-13, 'max':3e-13},
                     'sig2':{'init':2.3e-1, 'min':1e-1, 'max':3.8e-1},
                     'cen2':{'init':1489.57, 'min':1489.57-0.5, 'max':1489.57+0.5},
                     'bgl':{'init':5e-14, 'min':None, 'max':None}},

    1504.76: {'amp1':{'init':9e-13, 'min':6e-13, 'max':1.5e-12},
                     'sig1':{'init':6e-2, 'min':4e-2, 'max':8e-2},
                     'cen1':{'init':1504.76, 'min':1504.76-1, 'max':1504.76+0.2},
                     'amp2':{'init':2e-13, 'min':1e-13, 'max':5e-13},
                     'sig2':{'init':1.7e-1, 'min':1e-1, 'max':2.5e-1},
                     'cen2':{'init':1504.76, 'min':1504.76-1, 'max':1504.76+0.2},
                     'bgl':{'init':5e-14, 'min':None, 'max':None}},

    1467.08: {'amp1':{'init':2e-13, 'min':1.5e-13, 'max':5e-13},
                     'sig1':{'init':3e-2, 'min':1e-2, 'max':7e-2},
                     'cen1':{'init':1467.08, 'min':1467.08-0.5, 'max':1467.08+0.5},
                     'amp2':{'init':6.8e-14, 'min':5e-14, 'max':1.5e-13},
                     'sig2':{'init':1.3e-1, 'min':1e-1, 'max':2.5e-1},
                     'cen2':{'init':1467.08, 'min':1467.08-0.5, 'max':1467.08+0.5},
                     'bgl':{'init':5e-14, 'min':None, 'max':None}},

    1500.45: {'amp1':{'init':4e-13, 'min':2e-13, 'max':8e-13},
                     'sig1':{'init':6e-2, 'min':4e-2, 'max':8e-2},
                     'cen1':{'init':1500.45, 'min':1500.45-1, 'max':1500.45+0.2},
                     'amp2':{'init':1.6e-13, 'min':5e-14, 'max':2e-13},
                     'sig2':{'init':1.2e-1, 'min':1e-1, 'max':5e-1},
                     'cen2':{'init':1500.45, 'min':1500.45-1, 'max':1500.45+0.2},
                     'bgl':{'init':5e-14, 'min':None, 'max':None}},
}

In [ ]:
# for line in line_df_coadded['labline'].unique():
#     test_df = line_df_coadded[line_df_coadded['labline']==line].copy()
#     guess_fit = ModelFitting(test_df, line_mask_dict, disp_df, lsf_df, verbose=False)
#     if line in initial_guess_line_df:
#         print(f'fitting for line {line}')
#         guess_fit.fit_lines(double_guess = initial_guess_line_df[line])
#     else:
#         print(f'amp error for line {line}')
#         #guess_fit.fit_lines()
#         pass
#     test_df.to_pickle(f'data/test_df_{line}.pkl')

In [29]:
line_df_coadded = pd.read_pickle('line_df_coadded.pkl')

In [37]:
#Takes about half an hour on a desktop
# fitting = ModelFitting(line_df_coadded, line_mask_dict, disp_df, lsf_df, verbose=False)
blue_fitting = ModelFitting(blue_df_coadded, line_mask_dict, disp_df, lsf_df, verbose=False)
red_fitting = ModelFitting(red_df_coadded, line_mask_dict, disp_df, lsf_df, verbose=False)
# fitting.fit_lines()
blue_fitting.fit_lines()
red_fitting.fit_lines()

Fitting lines:  14%|█▍        | 1/7 [00:18<01:48, 18.09s/it]

Warning: redchi=0.465 — errors may be overestimated, no rescaling applied

Fitting lines:  29%|██▊       | 2/7 [00:30<01:14, 14.91s/it]

Warning: redchi=0.424 — errors may be overestimated, no rescaling applied

Fitting lines:  43%|████▎     | 3/7 [00:45<00:59, 14.75s/it]

Warning: redchi=0.277 — errors may be overestimated, no rescaling applied

Fitting lines: 100%|██████████| 7/7 [01:53<00:00, 16.15s/it]
Fitting lines:  92%|█████████▏| 11/12 [03:16<00:16, 16.23s/it]

Warning: redchi=0.346 — errors may be overestimated, no rescaling applied

Fitting lines: 100%|██████████| 12/12 [03:33<00:00, 17.81s/it]

In [38]:
line_df_coadded.to_pickle(os.path.join('data','line_df_coadded_bootstrapped_run2.pkl'))
red_df_coadded.to_pickle(os.path.join('data','red_df_coadded_bootstrapped_run2.pkl'))
blue_df_coadded.to_pickle(os.path.join('data','blue_df_coadded_bootstrapped_run2.pkl'))

In [15]:
line_df_coadded.to_pickle(os.path.join('data','line_df_coadded.pkl'))
red_df_coadded.to_pickle(os.path.join('data','red_df_coadded.pkl'))
blue_df_coadded.to_pickle(os.path.join('data','blue_df_coadded.pkl'))

In [ ]:
line_df.to_pickle(os.path.join('data','line_df_local.pkl'))
red_df.to_pickle(os.path.join('data','red_df.pkl'))
blue_df.to_pickle(os.path.join('data','blue_df.pkl'))

In [ ]:
#make an SNR cut to remove lines whose fit errors are high. This ensures we keep good fits only.
#first, make the cut based on the single gauss fit. Cut if fit SNR < data SNR
def SNR(signal, noise):
    #normalize the signal
    normsignal = signal/np.max(signal)
    normnoise = noise/np.max(noise)
    return np.mean(normsignal/normnoise)

def snr_mask(df, low, high):
    ratio = df.apply(lambda r: SNR(r['gauss_flux'], r['gauss_fluxerr']) /
                               SNR(r['flux'], r['fluxerr']), axis=1)
    return df[ratio.between(low, high)]

red_df_cut  = snr_mask(red_df,  1.3, 13)
blue_df_cut = snr_mask(blue_df, 1.3, 16)
line_df_cut = snr_mask(line_df, 0.8, 100)

# Coadd lines in velocity space
Coadding has to be done after the fits because of the convolution with the COS LSF (takes place in wavelength space).
Coadding by progression will allow me to reproduced the lyman alpha profile for each observation date.
If I coadd the emission line data and then fit a gaussian to them, that might give me some baseline parameter estimations.

In [ ]:
shift_all = True
line_prog_df = all_spectra.coaddvel(line_df_cut, columns=['transition', 'obsdate'], shift_all=shift_all)
blue_prog_df = all_spectra.coaddvel(blue_df_cut, columns=['transition'], shift_all=shift_all)
red_prog_df = all_spectra.coaddvel(red_df_cut, columns=['transition'], shift_all=shift_all)
prog_df = pd.concat([line_prog_df, blue_prog_df, red_prog_df], ignore_index=True, sort=False)

In [ ]:
line_prog_df.to_pickle(os.path.join('data','line_prog_df_local.pkl'))
red_prog_df.to_pickle(os.path.join('data','red_prog_df.pkl'))
blue_prog_df.to_pickle(os.path.join('data','blue_prog_df.pkl'))